Added dns resolution test

diff --git a/ssh-when-up b/ssh-when-up
--- a/ssh-when-up
+++ b/ssh-when-up
@@ -25,6 +25,16 @@ function sleepy() {
         fi
 }
 
+# first check if this is a hostname and if it is check if it can be resolved
+if echo $host | grep -E "^[0-9\.]+$" > /dev/null; then
+    echo "Connecting to IP address $host"
+else
+    if ! host $host > /dev/null; then
+        echo "Failed to do hostname resolution for $host"
+        exit 1
+    fi
+fi
+
 while true; do
         if ssh -o ConnectTimeout=2 $host id 2>1 | grep -q "uid="; then
             ssh $host
